services:

  database:
    restart: always
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: health_checker
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --save "" --appendonly no
    ports:
      - "6379:6379"
    restart: unless-stopped
    mem_limit: 64m

volumes:
  postgres_data: