server:
  port: 7070
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/health_check
    username: postgres
    password: postgres
  devtools:
    livereload:
      enabled: true
  jpa:
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: 'health'
  endpoint:
    health:
      show-details: never