server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: 'health'
  endpoint:
    health:
      show-details: never
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}