server:
  port: 7070
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/health_checker
    username: postgres
    password: postgres
  devtools:
    livereload:
      enabled: true
  jpa:
    show-sql: true
  session:
    store-type: redis
    redis:
      namespace: "health-checker:session"  # prefix keys Redis
      flush-mode: on-save                # save on changes
    timeout: 30m                         # session lifetime
  data:
    redis:
      host: localhost
      port: 6379
management:
  endpoints:
    web:
      exposure:
        include: 'health'
  endpoint:
    health:
      show-details: never