apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: prod
type: Opaque
stringData:
  DB_URL: jdbc:postgresql://postgres-service:5433/health_checker
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
