CREATE TABLE app_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE authority
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authority VARCHAR(255) NOT NULL
);

CREATE TABLE url
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url           VARCHAR(255) NOT NULL UNIQUE,
    is_up         BOOLEAN      NOT NULL DEFAULT false,
    failure_count BIGINT DEFAULT 0,
    last_update   TIMESTAMP DEFAULT NOW()
);

CREATE TABLE url_check_result
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    http_status      INTEGER,
    is_up            BOOLEAN NOT NULL,
    checked_at       TIMESTAMP,
    response_time_ms BIGINT,
    url_id           BIGINT,
    CONSTRAINT fk_url_check_result_url
        FOREIGN KEY (url_id)
            REFERENCES url (id)
);

CREATE TABLE user_authority
(
    authority_id BIGINT NOT NULL,
    user_id      BIGINT NOT NULL,
    PRIMARY KEY (authority_id, user_id),
    CONSTRAINT fk_user_authority_authority
        FOREIGN KEY (authority_id)
            REFERENCES authority (id),
    CONSTRAINT fk_user_authority_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (id)
);

CREATE TABLE user_url_subscription
(
    url_id  BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (url_id, user_id),
    CONSTRAINT fk_user_url_subscription_url
        FOREIGN KEY (url_id)
            REFERENCES url (id),
    CONSTRAINT fk_user_url_subscription_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (id)
);