INSERT INTO authority(authority)
VALUES ('USER'),
       ('ADMIN');

INSERT INTO url (url)
VALUES ('https://google.com'),
       ('https://facebook.com'),
       ('https://youtube.com'),
       ('https://twitter.com'),
       ('https://instagram.com'),
       ('https://linkedin.com'),
       ('https://pinterest.com'),
       ('https://reddit.com'),
       ('https://wikipedia.org'),
       ('https://github.com'),
       ('https://stackoverflow.com'),
       ('https://medium.com'),
       ('https://aws.amazon.com'),
       ('https://azure.microsoft.com'),
       ('https://cloud.google.com'),
       ('https://openai.com'),
       ('https://bbc.com'),
       ('https://cnn.com'),
       ('https://nytimes.com'),
       ('https://theguardian.com'),
       ('https://yahoo.com'),
       ('https://bing.com'),
       ('https://duckduckgo.com'),
       ('https://apple.com'),
       ('https://microsoft.com'),
       ('https://adobe.com'),
       ('https://spotify.com'),
       ('https://netflix.com'),
       ('https://airbnb.com'),
       ('https://uber.com'),
       ('https://dropbox.com'),
       ('https://quora.com'),
       ('https://tumblr.com'),
       ('https://wordpress.com'),
       ('https://etsy.com'),
       ('https://twitch.tv'),
       ('https://slack.com'),
       ('https://discord.com'),
       ('https://salesforce.com'),
       ('https://mozilla.org'),
       ('https://opera.com'),
       ('https://zoom.us'),
       ('https://bbc.co.uk'),
       ('https://washingtonpost.com'),
       ('https://forbes.com'),
       ('https://techcrunch.com'),
       ('https://kickstarter.com');